### ISSUE TITLE
Include "micronaut-flyway" in Micronaut's BOM

### ISSUE THREAD

**Issue by x80486** [micronaut-projects/micronaut-configuration-flyway#1]
I'm using Micronaut's BOM `io.micronaut:micronaut-bom:1.0.0` and it can't find Flyway; there is only `1.0.0.RC1`.

Is it possible to include on upcoming releases?

**Comment by ilopmar** [comment]
Both Flyway and Liquibase will be included in the BOM in Micronaut 1.1.0: https://github.com/micronaut-projects/micronaut-core/commit/76933fa42b807a178daedf8c7c5999c2a62f6f12

At this moment you need to manually define the version: `compile "io.micronaut.configuration:micronaut-flyway:1.0.0.RC1"`
